services:
  mariadb:
    image: mariadb:12.3
    container_name: mdd-mariadb
    restart: on-failure:2
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_HOST_PORT:-3306}:3306"
    volumes:
      - mdd-mariadb-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 30s
      interval: 5s
      timeout: 5s
      retries: 10
 
volumes:
  mdd-mariadb-data: