logging.level.com.orion.mdd=DEBUG

# Hibernate génère/maj le schéma à partir des entités (dev uniquement)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true