spring.application.name=mdd
spring.profiles.active=dev
spring.config.import=optional:file:.env[.properties]

orion.mdd.jwt.secret=${JWT_SECRET}
orion.mdd.jwt.expiration-ms=${JWT_EXPIRATION_MS:86400000}
